package templates

var AppxModel = `// AUTO GENERATED BY appx-cli - DO NOT EDIT

package {{.Pkg}}

import (
	"appengine/datastore"
	"github.com/drborges/appx"
)

type {{.Name}}AppxModel struct {
	*{{.Name}}
	db *appx.Datastore
}

func (model *{{.Name}}AppxModel) WithEncodedKey(encoded string) *{{.Name}}AppxModel {
	key, _ := datastore.DecodeKey(encoded)
	model.SetKey(key)
	return model
}

func (model *{{.Name}}AppxModel) WithEncodedParentKey(encoded string) *{{.Name}}AppxModel {
	key, _ := datastore.DecodeKey(encoded)
	model.SetParentKey(key)
	return model
}

func (model *{{.Name}}AppxModel) With(data {{.Name}}) *{{.Name}}AppxModel {
	*model.{{.Name}} = data
	return model
}

func (model *{{.Name}}AppxModel) Save() error {
	return model.db.Save(model)
}

func (model *{{.Name}}AppxModel) Delete() error {
	return model.db.Delete(model)
}`
